GENERATING RANDOM DATASHEET

In [3]:
import numpy as np

In [ ]:
matrix =[]
rng = np.random.default_rng(seed=5)

x = rng.integers(0,100,4)
print(x)
arr = rng.random((3,5))*1+100

randitn = rng.integers(1,100,10)
print(randitn)
randomint= rng.integers(1,100,size=(3,3))
print(randomint)



[67 80  2 80]
[[36 88 19]
 [ 7 38 68]
 [13 87 34]]
