In [59]:
# Rows = students, Columns = subjects
import numpy as np

marks = np.array([
    [72, 85, 90, 68],
    [88, 79, 95, 92],
    [60, 70, 65, 58],
    [91, 89, 94, 99],
    [76, 84, 80, 73]
])


Average  per student

Average  per subject

Highest /lowest scores

Standard  deviation

Rank  students

Normalize  marks


In [54]:
avg = []

avg = np.mean(marks, axis=1)
print("Average Per Student is :")
for i in range(avg.shape[0]):
    print(i, avg[i])

Average Per Student is :
0 78.75
1 88.5
2 63.25
3 92.5
4 78.25


In [55]:
avg = []

avg = np.mean(marks, axis=0)
print("Average Per Subject is :")
for i in range(avg.shape[0]):
    print(i, avg[i])

Average Per Subject is :
0 77.4
1 81.4
2 84.8
3 77.4


In [60]:
print(np.max(marks))
print(np.min(marks))

99
58


In [38]:
rank = []
rank = np.sort(avg)

for i in range(avg.shape[0]):
    print(i ,rank[i])


0 73.6
1 75.4
2 76.4
3 77.8
4 78.8


In [40]:
print("Standard Deviation :", np.std(marks,axis=1))

Standard Deviation : [6.01331855 3.12409987 1.72046505 2.41660919 2.31516738]


In [52]:
#NORMALIZATION
print("MAX-MIN METHOD NORMALIZATIO\n")
norm = (marks - marks.min())/(marks.max()-marks.min())
print(norm)

# .........
print("Z-SCORE NORMALIZATION\n")
norm = (marks - np.mean(marks)) / np.std(marks)
print(norm)

MAX-MIN METHOD NORMALIZATIO

[[0.58974359 0.76923077 0.94871795 0.84615385 0.53846154]
 [0.25641026 0.38461538 0.43589744 0.33333333 0.48717949]
 [0.8974359  0.94871795 1.         0.87179487 0.92307692]
 [0.         0.12820513 0.07692308 0.17948718 0.05128205]
 [0.64102564 0.51282051 0.58974359 0.69230769 0.61538462]]
Z-SCORE NORMALIZATION

[[ 0.13453456  0.72312325  1.31171195  0.97537555 -0.03363364]
 [-0.95855873 -0.53813824 -0.36997004 -0.70630643 -0.20180184]
 [ 1.14354375  1.31171195  1.47988015  1.05945965  1.22762785]
 [-1.79939972 -1.37897923 -1.54714743 -1.21081103 -1.63123153]
 [ 0.30270276 -0.11771774  0.13453456  0.47087096  0.21861866]]
