In [2]:
import numpy as np
import math

In [3]:
sales_data = np.array( [
    [1, 120, 135, 150, 170, 190],
    [2, 80,  95,  110, 105, 115],
    [3, 200, 210, 230, 260, 300],
    [4, 150, 145, 160, 180, 210],
    [5, 60,  75,  90,  120, 140]
])


# for i in range(3):
#     print(sales_data[i])

# print(sales_data[:3])

# print(sales_data[np.where(sales_data[:,0]<4)])

# print(sales_data[:3,1:]) #Escapes the 1st column


#Print sum of sales yearly for each company 
# print(np.sum(sales_data,axis=0))

# print(np.sum(sales_data[:,1:],axis=0)) #removing 1st  column using slicing


#print minimum sales per resturant
print()
print(sales_data[1: ,:])









[[  2  80  95 110 105 115]
 [  3 200 210 230 260 300]
 [  4 150 145 160 180 210]
 [  5  60  75  90 120 140]]


Random Module
