In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


Creating Arrays


In [2]:
import numpy as np
arr = np.array([1,2,3])
arr =arr*2
print(arr)
# .....................................................
zeros = np.zeros((2,2))
print(zeros ,"\n")
# .....................................................
ones = np.ones((2,2))
print(ones , "\n")
# .....................................................
print("sum :\n", zeros+ones)
# .....................................................
full = np.full((2,2),7)
print("full constant value array :\n",full)
# .....................................................
#multiplication of two arrays:
arr1 = np.array([1,2,3])
print(arr.dot(arr1))



[2 4 6]
[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]] 

sum :
 [[1. 1.]
 [1. 1.]]
full constant value array :
 [[7 7]
 [7 7]]
28


Vectors , Matrix and Tensor



In [ ]:
import numpy as np
vector = np.array([1,2,3])
print("Vector :",vector)

matrix = np.array([[1,2,3],
                   [3,4,5]])
print("Matrix :", matrix)

tensor = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print("Tensor :", tensor)

Vector : [1 2 3]
Matrix : [[1 2 3]
 [3 4 5]]
Tensor : [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Properties Of Arrays


In [ ]:
import numpy as np
arr = np.array([[1,2,3],
                [11,22,33]])
print("Size " , arr.size)
print("Shape ", arr.shape)
print("Dimension " , arr.ndim)
print("Data type :", arr.dtype)

Size  6
Shape  (2, 3)
Dimension  2
Data type : int64


Arrays Reshaping

In [3]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape(4,3)
print("Reshaped Array is : ",reshaped )

transposed = reshaped.T
print("Transposed Array : ", transposed)

matrix = np.array([[1,2,3],
                    [4,5,6]])
transpose = matrix.T
print("Transpoed Matrix : " ,transpose)


flattened = arr.flatten()
print("Flatt Array is :", flattened)  #changes the original array and copied in flattened

#Return view, instead of copy : it donot change the original array just view it
raveled = arr.ravel()
print(raveled)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array is :  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Transposed Array :  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Transpoed Matrix :  [[1 4]
 [2 5]
 [3 6]]
Flatt Array is : [ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
