SlICING 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing :",arr[2:7])
print("SLicing with Step" , arr[1:8:2])
print("Negative Indexing " , arr[-3])

Basic Slicing : [3 4 5 6 7]
SLicing with Step [2 4 6 8]
Negative Indexing  7


In [3]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element  :" , arr2d[0,0])
print("Entire row ", arr2d[1])
print("Entire column ", arr2d[:,1])


Specific Element  : 1
Entire row  [4 5 6]
Entire column  [2 5 8]


SORTING (axis)

In [4]:
unsorted = np.array([2,3,1,9,0,1,2,6,1,3])
print("Sorted Array is ", np.sort(unsorted))
unsorted2d = np.array([[6,1,0], [9,0,1] , [2,3,4]])
print("Sorted 2d Array column wise ", np.sort(unsorted2d , axis =0))
print("Sorted 2d Array row wise ", np.sort(unsorted2d , axis =1))


Sorted Array is  [0 1 1 1 2 2 3 3 6 9]
Sorted 2d Array column wise  [[2 0 0]
 [6 1 1]
 [9 3 4]]
Sorted 2d Array row wise  [[0 1 6]
 [0 1 9]
 [2 3 4]]


Filtering & and Mask 

In [5]:
import numpy as np
arr= np.arange(1,11)
print(arr[arr%2==0]) #We can Directly pass the codition in array instead of index 

mask = arr>5
print(arr[mask])  #This is called filter with mask  we can store an argument in a mask and 
                  #pass it to  array, here mask doesn't store any   values it store the expression.    

     


[ 2  4  6  8 10]
[ 6  7  8  9 10]


Indexing & compatibility

In [6]:
indices = [0,2,4]
print(arr[indices])

#..........................................................................

x = np.array([1,2,3])
y = np.array([3,4,4])
print(x.size == y.size)

[1 3 5]
True


np.where() FUNCTION  -------> np.where("Condition" , "what to do if condition true",
                                        if not true")

In [ ]:
arrr = np.array([1,2,3,4,5,6,7,8,9,10,11,22])
num = np.where(arrr>5 , arrr, arrr*2)
print(num)

nums = np.where(arrr>5 , True , False)
print(nums)
#It means if numbers gretaer than 5 it will print true;  else false 

 
where_result = arr>4
print(arr[np.where(where_result)]) 



[ 2  4  6  8 10  6  7  8  9 10 11 22]
[False False False False False  True  True  True  True  True  True  True]
[ 5  6  7  8  9 10]


Adding and Removing Elements , Rows and Columns


In [8]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],
              [0,1,0]])
ans = np.concatenate((a,b))
print(ans)



newRow = np.array([[1,2,2]])
newRowArray = np.vstack((a , newRow))
print(newRowArray)


newColumn = np.array([[1],[1]])
newColumnArray = np.hstack((b, newColumn))
print(newColumnArray)


z =np.array([1,2,3,4,5,6,67])
deleted = np.delete(z,1)
print("array after deletion ", deleted)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 0]]
[[1 2 3]
 [4 5 6]
 [1 2 2]]
[[7 8 9 1]
 [0 1 0 1]]
array after deletion  [ 1  3  4  5  6 67]
